/**
 * Downloads the app's fonts from Google and writes public/fonts/fonts.css.
 *
 * Serving them from this origin rather than a third party removes two outside
 * hosts from every cold start, lets the Content-Security-Policy forbid outside
 * connections outright, and makes the mushaf render offline without relying on
 * a runtime cache being warm.
 *
 * Only the Arabic and basic Latin subsets are kept. Cyrillic, Greek, and
 * Vietnamese are dead weight in a Quran app and roughly double the payload.
 *
 *   node scripts/build-fonts.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs'

/*
 * Noto Nastaliq Urdu is here for one reason: Urdu is not Arabic.
 *
 * Both are written in the Arabic script, so a naskh face renders Urdu without
 * complaint and the app looked finished. To someone who reads Urdu it is not:
 * Urdu is set in nastaliq, sloping down from right to left, and naskh reads
 * the way a serif newspaper face would read if it were used for handwriting.
 * The letters are right and the language looks wrong.
 *
 * It costs more than the others -- nastaliq needs thousands of ligatures to
 * join at the correct angle, and there is no honest way to make that small.
 * It is only ever fetched by a reader who has chosen Urdu, because nothing
 * else on the page asks for it.
 */
const FAMILIES =
  'family=Aref+Ruqaa:wght@400;700&family=Amiri:wght@400;700&family=Amiri+Quran' +
  '&family=IBM+Plex+Sans+Arabic:wght@400;500;600' +
    // One weight only: Google returns byte-identical files for 400 and 600,
  // because the family has no true bold. Asking for both shipped the same
  // 239 KB twice. Urdu typography does not lean on bold anyway.
  '&family=Noto+Nastaliq+Urdu:wght@400'

// Google serves woff2 only to browsers that advertise support.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

const OUT = 'public/fonts'
mkdirSync(OUT, { recursive: true })

const css = await (
  await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, {
    headers: { 'User-Agent': UA },
  })
).text()

const faces = []
for (const block of css.split('@font-face').slice(1)) {
  const fam = block.match(/font-family:\s*'([^']+)'/)?.[1]
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400'
  const url = block.match(/url\((https[^)]+)\)/)?.[1]
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim() ?? ''
  if (fam && url) faces.push({ fam, weight, url, range })
}

const keep = []
const seenLatin = new Set()
for (const f of faces) {
  if (/U\+0600|U\+06|U\+FB5|U\+FE7|U\+08A0/.test(f.range)) {
    keep.push({ ...f, kind: 'arabic' })
    continue
  }
  // One plain-Latin subset per family and weight, for the English interface.
  const key = `${f.fam}|${f.weight}`
  if (/U\+0000-00FF/.test(f.range) && !seenLatin.has(key)) {
    seenLatin.add(key)
    keep.push({ ...f, kind: 'latin' })
  }
}

let bytes = 0
for (const f of keep) {
  f.file = `${f.fam.toLowerCase().replace(/[^a-z]+/g, '-')}-${f.weight}-${f.kind}.woff2`
  const buf = Buffer.from(await (await fetch(f.url)).arrayBuffer())
  writeFileSync(`${OUT}/${f.file}`, buf)
  bytes += buf.length
}

const out = [
  '/* Generated by scripts/build-fonts.mjs — do not edit by hand. */',
  '',
  ...keep.flatMap((f) => [
    '@font-face {',
    `  font-family: '${f.fam}';`,
    '  font-style: normal;',
    `  font-weight: ${f.weight};`,
    '  font-display: swap;',
    // Relative to this stylesheet, so it survives being served from a subpath.
    `  src: url('./${f.file}') format('woff2');`,
    ...(f.range ? [`  unicode-range: ${f.range};`] : []),
    '}',
    '',
  ]),
]
writeFileSync(`${OUT}/fonts.css`, out.join('\n'))

console.log(`kept ${keep.length} of ${faces.length} faces`)
console.log(`${OUT}/fonts.css written, ${(bytes / 1024).toFixed(0)} KB of woff2`)
